language: python

python:
  - "2.7"

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements-dev.txt
  - python setup.py build_ext --inplace
  - python setup.py install

script: nosetests
